env:
  global:
    - CODECOV_TOKEN="393cb0de-bd78-4104-bbea-d073c1091479
language: node_js
node_js:
  - 'node'
install:
  - npm install -g codecov
before_script:
  - npm install
script:
  - npm test
  - codecov
